config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  devise_for :users, :controllers => { registrations: 'users/registrations'}

  root "home#index"

  resources :categories
  resources :products

  get 'download' => 'categories#download'

  get 'download_pdf' => 'categories#download_pdf'

  resource :verifications

  get 'users' => 'users#index'
  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	require "prawn"
  require "prawn/table"
	
	before_filter :authenticate_user!

	def index
		@categories = Category.all
	end

	def show
	end

	def new
		@category = Category.new
	end

	def create
	end

	def destroy
	end

	#Download html in pdf formate with wicked_pdf
	def download_pdf
		@categories = Category.all
		html = render_to_string :action => :index, :layout => "pdf.html.erb", :locals => {:categories => @categories}
		# Also pass layout as false
  	pdf = WickedPdf.new.pdf_from_string(html)
  	send_data(pdf, :filename => "categories.pdf", :disposition => 'attachment')
	end

	#Download html in pdf formate with the prawn
  def download
    @categories = Category.all
    respond_to do |format|
      format.pdf do
        pdf = Prawn::Document.new
        table_data = Array.new
        table_data << ["Category name"]
        @categories.each do |c|
          table_data << [c.name]
        end
        pdf.table(table_data, :width => 500, :cell_style => { :inline_format => true })
        #send_data pdf.render, filename: 'test.pdf', type: 'application/pdf', :disposition => 'inline'
        send_file '/home/nikhil/Downloads/test.pdf', :type => 'application/pdf', :disposition => 'attachment'
      end
    end
  end

	private

		def category_params
			params.require(:ctaegory).permit(:name)
		end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => "form-horizontal category" } do |f| %>

  <% if @category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.name %></td>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

<%= link_to "Download PDF(Download html in pdf formate with wicked_pdf)",
            download_pdf_path,
            :class => 'btn btn-primary' %>

<%= link_to "Download(Download html in pdf formate with the Prawn)",
            download_path,
            :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>